# Generated by Django 4.0.3 on 2023-08-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0004_k_washing_direction_k_washing_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='direction',
            field=models.CharField(choices=[('1', '방향1'), ('2', '방향2'), ('3', '방향3'), ('4', '방향4')], max_length=5),
        ),
        migrations.AlterField(
            model_name='k_washing',
            name='floor',
            field=models.CharField(choices=[('1', '1층'), ('2', '2층'), ('3', '3층'), ('4', '4층')], max_length=5),
        ),
    ]
