# Generated by Django 4.0.3 on 2023-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0005_alter_k_washing_direction_alter_k_washing_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_washing',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
