# Generated by Django 4.0.3 on 2023-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0007_k_washing_moretime_alter_k_washing_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='content',
            field=models.CharField(choices=[('1', '없음'), ('2', '빨래가 끝난 후 바구니에 넣어주세요.'), ('3', '세탁이 빨리 끝날 수 있습니다.'), ('4', '시간이 오래걸립니다.')], max_length=5),
        ),
    ]
