# Generated by Django 4.0.3 on 2023-08-20 14:28

from django.db import migrations
import k_washing.models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0010_k_washing_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='moretime',
            field=k_washing.models.IntegerRangeField(null=True),
        ),
    ]
