# Generated by Django 4.0.3 on 2023-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0012_alter_k_washing_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='content',
            field=models.CharField(choices=[('없음', '1'), ('빨래가 끝난 후 바구니에 넣어주세요.', '2'), ('세탁이 빨리 끝날 수 있습니다.', '3'), ('시간이 오래걸립니다.', '4'), ('향긋한 빨래 되세요:)', '5'), ('K세탁 폼 미쳤다.', '6')], max_length=25),
        ),
    ]
