# Generated by Django 4.0.3 on 2023-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0014_alter_k_washing_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='content',
            field=models.CharField(choices=[('없음', '없음'), ('빨래가 끝난 후 바구니에 넣어주세요.', '빨래가 끝난 후 바구니에 넣어주세요.'), ('세탁이 빨리 끝날 수 있습니다.', '세탁이 빨리 끝날 수 있습니다.'), ('시간이 오래걸립니다.', '시간이 오래걸립니다.'), ('향긋한 빨래 되세요:)', '향긋한 빨래 되세요:)'), ('K세탁 폼 미쳤다.', 'K세탁 폼 미쳤다.')], max_length=25),
        ),
    ]
