# Generated by Django 4.0.3 on 2023-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0016_remove_k_washing_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
