# Generated by Django 4.0.3 on 2023-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0020_k_washing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='state',
            field=models.IntegerField(choices=[(0, 'State 0'), (1, 'State 1')], default=0),
        ),
    ]
