# Generated by Django 4.0.3 on 2023-08-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0021_alter_k_washing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='k_washing_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_1', models.IntegerField()),
                ('direction_1', models.IntegerField()),
                ('time_first', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='k_washing',
            name='state',
        ),
        migrations.AlterField(
            model_name='k_washing',
            name='finish_time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
