# Generated by Django 4.0.3 on 2023-08-27 17:53

from django.db import migrations
import k_washing.models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0022_alter_k_washing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing',
            name='time',
            field=k_washing.models.IntegerRangeField(null=True),
        ),
    ]
