# Generated by Django 4.0.3 on 2023-08-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0022_k_washing_state_remove_k_washing_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_washing_state',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
