# Generated by Django 4.0.3 on 2023-08-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0023_k_washing_state_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_washing_state',
            name='pk_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
