# Generated by Django 4.0.3 on 2023-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_washing', '0024_k_washing_state_pk_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_washing_state',
            name='direction_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='k_washing_state',
            name='floor_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='k_washing_state',
            name='pk_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='k_washing_state',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='k_washing_state',
            name='time_first',
            field=models.IntegerField(null=True),
        ),
    ]
